---
name: semantic-release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_READONLY_ACCESS_TO_MODULES }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          extra_plugins: |
           conventional-changelog-conventionalcommits@8.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run custom action
        uses: opencepk/opencepk-module-ghactions-common/github-flow-update-release-notes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
